/home/ubuntu/workspace/src/a.out "cd"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "ls && cd"
/home/ubuntu/workspace/src/a.out "cd tests && ls"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "cd"
/home/ubuntu/workspace/src/a.out "cd src; ls"
/home/ubuntu/workspace/src/a.out "cd && cd tests; ls; cd - && cd"
