/home/ubuntu/workspace/src/a.out "cd"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "ls && cd"
/home/ubuntu/workspace/src/a.out "cd workspace && ls"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "cd -"
/home/ubuntu/workspace/src/a.out "cd"
/home/ubuntu/workspace/src/a.out "cd workspace; cd src; ls"
/home/ubuntu/workspace/src/a.out "cd && cd workspace; cd tests; ls; cd - && cd"
