/home/ubuntu/workspace/src/a.out "exit # exiting shell"
/home/ubuntu/workspace/src/a.out "ls -a; exit # listing all files and directories and exiting shell"
/home/ubuntu/workspace/src/a.out "cal; exit; #printing calendar and exiting shell"
/home/ubuntu/workspace/src/a.out "cal 7 2010; date; exit; #printing calendar and date and exiting shell"
/home/ubuntu/workspace/src/a.out "ls -a #listing all directories and files"
/home/ubuntu/workspace/src/a.out "ls -l #long-listing format"
/home/ubuntu/workspace/src/a.out "cal # displays calendar and highlights today's date"
/home/ubuntu/workspace/src/a.out "cal 7 2010 #displays calendar for July 2010"
/home/ubuntu/workspace/src/a.out "date +%D #displays date"
/home/ubuntu/workspace/src/a.out "date +%X #displays time in hh:mm:ss format"