/home/ubuntu/workspace/src/a.out "exit"
/home/ubuntu/workspace/src/a.out "ls -a; exit"
/home/ubuntu/workspace/src/a.out "ls -l && exit"
/home/ubuntu/workspace/src/a.out "ls && exit || ls -l"
/home/ubuntu/workspace/src/a.out "echo \"this is a test\"; exit"
/home/ubuntu/workspace/src/a.out "echo hello; echo world! || exit"
/home/ubuntu/workspace/src/a.out "cal; exit;"
/home/ubuntu/workspace/src/a.out "date +%D; exit"
/home/ubuntu/workspace/src/a.out "date +%X && exit"
/home/ubuntu/workspace/src/a.out "cal && date +%D; exit"
/home/ubuntu/workspace/src/a.out "cal 7 2010; date; exit;"
/home/ubuntu/workspace/src/a.out "date +%D; date +%X && exit'"