/home/ubuntu/workspace/src/a.out "exit"
/home/ubuntu/workspace/src/a.out "ls -a; exit #testing"
/home/ubuntu/workspace/src/a.out "ls -l && exit"
/home/ubuntu/workspace/src/a.out "ls && exit || ls -l"
/home/ubuntu/workspace/src/a.out "echo \"this is a test\"; exit"
/home/ubuntu/workspace/src/a.out "echo hello; echo world! || exit"
/home/ubuntu/workspace/src/a.out "cal; exit; ###testing"
/home/ubuntu/workspace/src/a.out "date +%D; exit"
/home/ubuntu/workspace/src/a.out "date +%X && exit #printing out time and exiting"
/home/ubuntu/workspace/src/a.out "cal && date +%D; exit"
/home/ubuntu/workspace/src/a.out "cal 7 2010; date; exit;"
/home/ubuntu/workspace/src/a.out "date +%D; date +%X && exit"
/home/ubuntu/workspace/src/a.out "[ /home ] && exit ## testing"
/home/ubuntu/workspace/src/a.out "test -e main.cpp && echo hello; exit"
/home/ubuntu/workspace/src/a.out "[ -f main.cpp ] || ls -a && exit"
