/home/ubuntu/workspace/src/a.out "ls; ls -a"
/home/ubuntu/workspace/src/a.out "ls && ls -l"
/home/ubuntu/workspace/src/a.out "ls && ls -a || ls -l"
/home/ubuntu/workspace/src/a.out "echo this; echo is && echo a; echo test"
/home/ubuntu/workspace/src/a.out "echo hello && echo world"
/home/ubuntu/workspace/src/a.out "echo hello; echo world || echo there"
/home/ubuntu/workspace/src/a.out "cal; date;"
/home/ubuntu/workspace/src/a.out "cal 7 2010; date +%D"
/home/ubuntu/workspace/src/a.out "date; date +%X"
