/home/ubuntu/workspace/src/a.out "(echo hello world) #######first test"
/home/ubuntu/workspace/src/a.out "(ls && echo this is a test) || (cal; date)"
/home/ubuntu/workspace/src/a.out "clear && (echo A && echo B) || (echo C && echo D)"
/home/ubuntu/workspace/src/a.out "(ls -l && echo A) || (echo B && ls -a"
/home/ubuntu/workspace/src/a.out "(echo hello; echo world) && (echo this is a test && cal)"
/home/ubuntu/workspace/src/a.out "(cal || date +%D) && cal 12 2016 #testing"
/home/ubuntu/workspace/src/a.out "(mkdir temp_test && echo made temporary directory) || exit"
/home/ubuntu/workspace/src/a.out "rm -r temp_test && (echo removed temporary directory && ls) || (echo directory could not be removed; exit)"
/home/ubuntu/workspace/src/a.out "test -e main.cpp && ((echo A && echo B) || (echo C && echo D))"
/home/ubuntu/workspace/src/a.out "(clear && exit) || exit ####last test"
