/home/ubuntu/workspace/src/a.out "ls"
/home/ubuntu/workspace/src/a.out "ls -a"
/home/ubuntu/workspace/src/a.out "ls -l"
/home/ubuntu/workspace/src/a.out "echo \"this is a test\""
/home/ubuntu/workspace/src/a.out "echo \"hello world\""
/home/ubuntu/workspace/src/a.out "cal"
/home/ubuntu/workspace/src/a.out "cal 7 2010"
/home/ubuntu/workspace/src/a.out "date"
/home/ubuntu/workspace/src/a.out "date +%D"
/home/ubuntu/workspace/src/a.out "date +%b-%d-%Y"
/home/ubuntu/workspace/src/a.out "date +%X"
/home/ubuntu/workspace/src/a.out "ps"