/home/ubuntu/workspace/src/a.out "ls"
/home/ubuntu/workspace/src/a.out "echo hello"
/home/ubuntu/workspace/src/a.out "echo world"
/home/ubuntu/workspace/src/a.out "echo \"this is a test\""
/home/ubuntu/workspace/src/a.out "cal"
/home/ubuntu/workspace/src/a.out "cal 7 2010"
/home/ubuntu/workspace/src/a.out "ls -a"
/home/ubuntu/workspace/src/a.out "ls -l"
/home/ubuntu/workspace/src/a.out "date +%D"
/home/ubuntu/workspace/src/a.out "date +%X"