/home/ubuntu/workspace/src/a.out "test -e main.cpp"
/home/ubuntu/workspace/src/a.out "[ -e /home ] ###checking if it exists"
/home/ubuntu/workspace/src/a.out "test -f /home/ubuntu/workspace/src"
/home/ubuntu/workspace/src/a.out "[ -f main.cpp ]"
/home/ubuntu/workspace/src/a.out "test -d /home"
/home/ubuntu/workspace/src/a.out "[ -d main.cpp ]"
/home/ubuntu/workspace/src/a.out "test main.cpp ##no flag from user"
/home/ubuntu/workspace/src/a.out "[ /home/ubuntu/workspace/src ]"
/home/ubuntu/workspace/src/a.out "test -e main.cpp && echo hello"
/home/ubuntu/workspace/src/a.out "[ -f main.cpp ] || ls -a"
/home/ubuntu/workspace/src/a.out "test -d main.cpp; ls -l"
/home/ubuntu/workspace/src/a.out "exit #exiting"
